name: cs10_z100_pos_printer
description: "A Flutter plugin for printing on CS10-Z100 POS terminals."
version: 0.0.1
homepage: https://github.com/AndresMontaniv/cs10_z100_pos_printer
repository: https://github.com/AndresMontaniv/cs10_z100_pos_printer
issue_tracker: https://github.com/AndresMontaniv/cs10_z100_pos_printer/issues 

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.andresmontano.cs10_z100_pos_printer
        pluginClass: Cs10Z100PosPrinterPlugin
